name: BetterInventories
version: '0.1'
main: net.ajay.betterInventories.BetterInventories
api-version: '1.21'
authors: [ Ajay ]


commands: 
  echest:
    description: "Shortcut for your ender chest."
    permission-message: "Can you see me?"
